name: Deploy Static Site

on:
  push:
    branches:
      - main
  workflow_dispatch:

jobs:
  build-and-deploy:
    runs-on: ubuntu-latest

    steps:
      # Checkout the repository code
      - name: Checkout
        uses: actions/checkout@v4

      # Set up Node.js (if your site uses Node-based tools like npm for building)
      - name: Setup Node
        uses: actions/setup-node@v4
        with:
          node-version: '20'
          cache: 'npm'

      # Install dependencies (modify if using a different package manager or tool)
      - name: Install Dependencies
        run: npm install

      # Build the static site (replace with your build command)
      - name: Build
        run: npm run build  # e.g., `jekyll build`, `hugo`, or custom script

      # Deploy to GitHub Pages
      - name: Deploy to GitHub Pages
        uses: peaceiris/actions-gh-pages@v4
        with:
          github_token: ${{ secrets.GITHUB_TOKEN }}
          publish_dir: ./dist  # Replace with your output directory (e.g., `_site` for Jekyll)
          force_orphan: true
          user_name: 'github-actions[bot]'
          user_email: 'github-actions[bot]@users.noreply.github.com'
          commit_message: 'Deploy to GitHub Pages'
